server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/users/**
        - id: book-service
          uri: ${BOOK_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/books/**
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/auth/**
        - id: borrow-service
          uri: ${BORROW_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/borrow/**
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/payments/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/notifications/**