server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: book-service
          uri: http://localhost:8082
          predicates:
            - Path=/books/**
        - id: borrow-service
          uri: http://localhost:8083
          predicates:
            - Path=/borrow/**
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/payments/**
        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**