server:
  port: ${PAYMENT_SERVICE_PORT:8084}

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/payment_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

vnpay:
  tmn-code: ${VNPAY_TMN_CODE:OAZCZS0F}
  hash-secret: ${VNPAY_HASH_SECRET:D0DTJ6R932I9FJPC6G9J3M0DSLIM6AEM}
  pay-url: ${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  return-url: ${VNPAY_RETURN_URL:http://localhost:8084/payments/vnpay/return}
  ipn-url: ${VNPAY_IPN_URL:http://localhost:8084/payments/vnpay/ipn}
  currency: VND
  version: 2.1.0
  command: pay
  order-type: other